clc
close all
clear all

format long

% =========================================================================
% MULTIPLE CLASSIFIER
% =========================================================================

results = importdata("data/multiple.csv");

% Number of times to run the ensemble method
runs = 3;

% Function to extract best hyperparameters
f = @extract_top_values;

%-----------
% JAPANESE |
% ----------

opts = delimitedTextImportOptions("NumVariables", 16);
opts.DataLines = [1, Inf];
opts.Delimiter = " ";
opts.VariableNames = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "TARGET"];
opts.VariableTypes = ["categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "double", "categorical", "categorical", "double", "categorical", "categorical", "double", "double", "categorical"];
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";
opts = setvaropts(opts, ["A1", "A4", "A5", "A6", "A7", "A9", "A10", "A12", "A13", "TARGET"], "EmptyFieldRule", "auto");
japanese = readtable("data/japanese/original/data.dat", opts);
clear opts

A1 = categorical(japanese.A1);
A1_encoding = onehotencode(A1,2);
A4 = categorical(japanese.A4);
A4_encoding = onehotencode(A4,2);
A5 = categorical(japanese.A5);
A5_encoding = onehotencode(A5,2);
A6 = categorical(japanese.A6);
A6_encoding = onehotencode(A6,2);
A7 = categorical(japanese.A7);
A7_encoding = onehotencode(A7,2);
A9_encoding = double(categorical(japanese.A9));
A10_encoding = double(categorical(japanese.A10));
A12_encoding = double(categorical(japanese.A12));
A13 = categorical(japanese.A13);
A13_encoding = onehotencode(A13,2);
TARGET = double(categorical(japanese.TARGET));

japanese_df = horzcat(A1_encoding(:,1:3),...
    normalize(japanese.A2),...
    normalize(japanese.A3),...
    A4_encoding(:,1:4),...
    A5_encoding(:,1:4),...
    A6_encoding(:,1:15),...
    A7_encoding(:,1:10),...
    normalize(japanese.A8),...
    A9_encoding(:,1),...
    A10_encoding(:,1),...
    normalize(japanese.A11),...
    A12_encoding(:,1),...
    A13_encoding(:,1:3),...
    normalize(japanese.A14),...
    normalize(japanese.A15),...
    TARGET(:,1));

cv = cvpartition(size(japanese_df,1),'HoldOut',0.3);
idx = cv.test;
dataTrain = japanese_df(~idx,:);
dataTest  = japanese_df(idx,:);
X_train = dataTrain(:, 1:end-1);
Y_train = dataTrain(:, end);
X_test = dataTest(:, 1:end-1);
Y_test = dataTest(:, end);


% -------------------------------------------------------------------------
% 3 classifiers
% -------------------------------------------------------------------------

% According to the saved instance of Single Classifiers these are the best
% 3 single classifiers

reserve = zeros(runs, 1);

for i = 1:runs
    
    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,3).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,3).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,3).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,3).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,3).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,3).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test), net2.predict(X_test), net3.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_3 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_3;

end

accuracy_best_of_3 = mean(reserve);

results(2,4) = accuracy_best_of_3;

% -------------------------------------------------------------------------
% 5 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs
    
    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,5).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,5).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,5).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,5).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,5).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,5).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,5).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,5).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,5).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,5).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_5 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_5;

end

accuracy_best_of_5 = mean(reserve);

results(3,4) = accuracy_best_of_5;


% -------------------------------------------------------------------------
% 7 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs
    
    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    net6 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(6),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(6),...
        'LayerBiasesInitializer','ones');
    
    net7 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,7).Var2(7),...
        'Activations','tanh',...
        'IterationLimit',f(5,7).Var1(7),...
        'LayerBiasesInitializer','ones');
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test),...
        net6.predict(X_test),...
        net7.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_7 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_7;

end

accuracy_best_of_7 = mean(reserve);

results(4,4) = accuracy_best_of_7;


% -------------------------------------------------------------------------
% 9 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs
    
    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    net6 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(6),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(6),...
        'LayerBiasesInitializer','ones');
    
    net7 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(7),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(7),...
        'LayerBiasesInitializer','ones');
    
    net8 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(8),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(8),...
        'LayerBiasesInitializer','ones');
    
    net9 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,9).Var2(9),...
        'Activations','tanh',...
        'IterationLimit',f(5,9).Var1(9),...
        'LayerBiasesInitializer','ones');
    
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test),...
        net6.predict(X_test),...
        net7.predict(X_test),...
        net8.predict(X_test),...
        net9.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_9 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_9;

end

accuracy_best_of_9 = mean(reserve);

results(5,4) = accuracy_best_of_9;

% -------------------------------------------------------------------------
% 11 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs

    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    net6 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(6),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(6),...
        'LayerBiasesInitializer','ones');
    
    net7 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(7),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(7),...
        'LayerBiasesInitializer','ones');
    
    net8 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(8),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(8),...
        'LayerBiasesInitializer','ones');
    
    net9 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(9),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(9),...
        'LayerBiasesInitializer','ones');
    
    net10 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(10),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(10),...
        'LayerBiasesInitializer','ones');
    
    net11 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,11).Var2(11),...
        'Activations','tanh',...
        'IterationLimit',f(5,11).Var1(11),...
        'LayerBiasesInitializer','ones');
    
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test),...
        net6.predict(X_test),...
        net7.predict(X_test),...
        net8.predict(X_test),...
        net9.predict(X_test),...
        net10.predict(X_test),...
        net11.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_11 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_11;

end

accuracy_best_of_11 = mean(reserve);

results(6,4) = accuracy_best_of_11;

% -------------------------------------------------------------------------
% 13 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs

    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    net6 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(6),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(6),...
        'LayerBiasesInitializer','ones');
    
    net7 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(7),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(7),...
        'LayerBiasesInitializer','ones');
    
    net8 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(8),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(8),...
        'LayerBiasesInitializer','ones');
    
    net9 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(9),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(9),...
        'LayerBiasesInitializer','ones');
    
    net10 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(10),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(10),...
        'LayerBiasesInitializer','ones');
    
    net11 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(11),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(11),...
        'LayerBiasesInitializer','ones');
    
    net12 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(12),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(12),...
        'LayerBiasesInitializer','ones');
    
    net13 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,13).Var2(13),...
        'Activations','tanh',...
        'IterationLimit',f(5,13).Var1(13),...
        'LayerBiasesInitializer','ones');
    
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test),...
        net6.predict(X_test),...
        net7.predict(X_test),...
        net8.predict(X_test),...
        net9.predict(X_test),...
        net10.predict(X_test),...
        net11.predict(X_test),...
        net12.predict(X_test),...
        net13.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_13 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_13;

end

accuracy_best_of_13 = mean(reserve);

results(7,4) = accuracy_best_of_13;


% -------------------------------------------------------------------------
% 15 classifiers
% -------------------------------------------------------------------------

reserve = zeros(runs,1);

for i = 1:runs

    net1 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(1),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(1),...
        'LayerBiasesInitializer','ones');
    
    net2 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(2),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(2),...
        'LayerBiasesInitializer','ones');
    
    net3 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(3),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(3),...
        'LayerBiasesInitializer','ones');
    
    net4 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(4),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(4),...
        'LayerBiasesInitializer','ones');
    
    net5 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(5),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(5),...
        'LayerBiasesInitializer','ones');
    
    net6 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(6),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(6),...
        'LayerBiasesInitializer','ones');
    
    net7 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(7),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(7),...
        'LayerBiasesInitializer','ones');
    
    net8 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(8),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(8),...
        'LayerBiasesInitializer','ones');
    
    net9 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(9),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(9),...
        'LayerBiasesInitializer','ones');
    
    net10 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(10),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(10),...
        'LayerBiasesInitializer','ones');
    
    net11 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(11),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(11),...
        'LayerBiasesInitializer','ones');
    
    net12 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(12),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(12),...
        'LayerBiasesInitializer','ones');
    
    net13 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(13),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(13),...
        'LayerBiasesInitializer','ones');
    
    net14 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(14),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(14),...
        'LayerBiasesInitializer','ones');
    
    net15 = fitcnet(X_train, Y_train,...
        'LayerSizes', f(5,15).Var2(15),...
        'Activations','tanh',...
        'IterationLimit',f(5,15).Var1(15),...
        'LayerBiasesInitializer','ones');
    
    
    % Thus by comparing the prediction with and using the majority vote
    % criteria:
    prediction = [net1.predict(X_test),...
        net2.predict(X_test),...
        net3.predict(X_test),...
        net4.predict(X_test),...
        net5.predict(X_test),...
        net6.predict(X_test),...
        net7.predict(X_test),...
        net8.predict(X_test),...
        net9.predict(X_test),...
        net10.predict(X_test),...
        net11.predict(X_test),...
        net12.predict(X_test),...
        net13.predict(X_test),...
        net14.predict(X_test),...
        net15.predict(X_test)];
    final_decision = mode(prediction,2);
    
    accuracy_best_of_15 = sum(final_decision == Y_test)/length(final_decision);

    reserve(i,1) = accuracy_best_of_15;

end

accuracy_best_of_15 = mean(reserve);

results(8,4) = accuracy_best_of_15;


writematrix(results,'data/multiple.csv')
















function top_n_values = extract_top_values(column_num, n)
    T = readtable("data/single.csv");
    
    % Choose the column based on which you want to extract the top values
    column_of_interest = ['Var', num2str(column_num)];
    
    % Sort the table based on the chosen column
    sorted_T = sortrows(T, column_of_interest, 'descend');
    
    % Extract the top n rows
    top_n_rows = sorted_T(1:n, :);
    
    % Extract the values from the first and second columns of the top n rows
    top_n_values = top_n_rows(:, {'Var1', 'Var2'});
end
